
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO: update}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable debug logging for attendance service to troubleshoot save behavior
logging.level.com.vansh.manger.Manger.Service.AttendanceService=debug

jwt.secret=${JWT_SECRET}


spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=true


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.base-folder=manger

resend.from.email = ${RESEND_FROM_EMAIL}
resend.api.key = ${RESEND_API_KEY}
