
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO: update}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Enable debug logging for attendance service to troubleshoot save behavior
logging.level.com.vansh.manger.Manger.Service.AttendanceService=debug

jwt.secret=${JWT_SECRET}
#Gmail SMTP Config
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:465}
spring.mail.protocol=smtps
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtps.ssl.enable=true
spring.mail.properties.mail.smtps.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true


cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}
cloudinary.base-folder=manger
